include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    unnecessary_library_name: ignore